os: 
 - linux
 - windows
 - macos
language: node_js
node_js:
  - 7
env: KACPER=Matrixtest
script:
  - echo $KACPER
  - npm start
#jobs:
 # include: 
 #   - env: KACPER=ssem
 #   - env: KACPER=ZycieCiZbrzydlo
